export { ReactComponent as Athletes } from "./athletes.svg"
export { ReactComponent as Highlight } from "./highlight.svg"
export { ReactComponent as Logout } from "./logout.svg"
export { ReactComponent as Settings } from "./settings.svg"
export { ReactComponent as Teams } from "./teams.svg"
export { ReactComponent as Tournaments } from "./tournaments.svg"
export { ReactComponent as Search } from "./search.svg"
export { ReactComponent as Back } from "./back.svg"